/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/forgot` | `/forgot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pollView` | `/pollView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/helper/Background`; params?: Router.UnknownInputParams; } | { pathname: `/helper/categories`; params?: Router.UnknownInputParams; } | { pathname: `/helper/DropdownComponent`; params?: Router.UnknownInputParams; } | { pathname: `/helper/DurationCountDown`; params?: Router.UnknownInputParams; } | { pathname: `/helper/Gauge`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/vote/[poll_id]`, params: Router.UnknownInputParams & { poll_id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/forgot` | `/forgot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(login)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pollView` | `/pollView`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownOutputParams; } | { pathname: `/helper/Background`; params?: Router.UnknownOutputParams; } | { pathname: `/helper/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/helper/DropdownComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/helper/DurationCountDown`; params?: Router.UnknownOutputParams; } | { pathname: `/helper/Gauge`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/vote/[poll_id]`, params: Router.UnknownOutputParams & { poll_id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/forgot${`?${string}` | `#${string}` | ''}` | `/forgot${`?${string}` | `#${string}` | ''}` | `${'/(login)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(login)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pollView${`?${string}` | `#${string}` | ''}` | `/pollView${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/context/UserContext${`?${string}` | `#${string}` | ''}` | `/helper/Background${`?${string}` | `#${string}` | ''}` | `/helper/categories${`?${string}` | `#${string}` | ''}` | `/helper/DropdownComponent${`?${string}` | `#${string}` | ''}` | `/helper/DurationCountDown${`?${string}` | `#${string}` | ''}` | `/helper/Gauge${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/forgot` | `/forgot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(login)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pollView` | `/pollView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/context/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/helper/Background`; params?: Router.UnknownInputParams; } | { pathname: `/helper/categories`; params?: Router.UnknownInputParams; } | { pathname: `/helper/DropdownComponent`; params?: Router.UnknownInputParams; } | { pathname: `/helper/DurationCountDown`; params?: Router.UnknownInputParams; } | { pathname: `/helper/Gauge`; params?: Router.UnknownInputParams; } | `/+not-found` | `/vote/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/vote/[poll_id]`, params: Router.UnknownInputParams & { poll_id: string | number; } };
    }
  }
}
